version: 0.2
env:
  secrets-manager:
     DB_INFO: arn:aws:secretsmanager:us-east-1:957180890197:secret:DB_INFO_PRODUCTION-UKQfnj
phases:
  install:
    commands:
      - git config --global credential.helper '!aws --region us-east-1 codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  pre_build:
    commands:
      - npm install
      - npm install -g cross-env
      - npm install jq
      - npm install --location=global cross-env cross-var-no-babel
  build:
    commands:
      - echo "In the building process"
      - export MONGO_DATABASE=$(echo "$DB_INFO" | jq -r '.MONDODB')
      - export NODE_ENV=$(echo "$DB_INFO" | jq -r '.NODE_ENV')
      - npm run deploy-production
